# Generated by Django 4.1 on 2022-12-14 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_client_service_rendered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='service_rendered',
            field=models.ForeignKey(blank=True, db_column='service_rendered', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.service'),
        ),
    ]
