# Generated by Django 4.1 on 2022-12-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_client_service_rendered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='service_rendered',
            field=models.CharField(default='Web Development', max_length=40),
        ),
    ]
