# Generated by Django 4.1 on 2022-12-16 01:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_service_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='code',
        ),
        migrations.AlterField(
            model_name='client',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.CharField(default='active', max_length=30),
        ),
    ]
