# Generated by Django 4.1 on 2022-12-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_products_code_alter_client_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='service_id',
            field=models.CharField(default='Web Development', max_length=40),
        ),
    ]
