# Generated by Django 4.1 on 2022-12-16 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_products_service_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='School Name', max_length=253)),
                ('client_name', models.CharField(max_length=200)),
                ('amount', models.FloatField(default=0)),
                ('payment_method', models.CharField(max_length=200)),
                ('payment_receipt', models.ImageField(blank=True, null=True, upload_to='')),
                ('transaction_id', models.CharField(max_length=200, unique=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
