# Generated by Django 4.1 on 2023-02-25 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_date']},
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('github_repo', models.URLField()),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('github_repo', models.URLField()),
                ('is_completed', models.BooleanField(blank=True, default=False, null=True)),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('time_spent', models.CharField(choices=[('1 Hour', '1 Hour'), ('2 Hours', '2 Hours'), ('3 Hours', '3 Hours'), ('4 Hours', '4 Hours'), ('5 Hours', '5 Hours'), ('6 Hours', '6 Hours'), ('7 Hours', '7 Hours'), ('8 Hours', '8 Hours')], max_length=20)),
                ('date_submitted', models.DateField()),
                ('task_done_on_above_mentioned_date', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
