# Generated by Django 4.1 on 2023-02-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_transaction_options_task_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_repo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
