# Generated by Django 4.1 on 2022-12-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(default='Frontend Developer', max_length=255),
        ),
    ]
